services:
  app:
    container_name: obsidian_rest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - "/home/rob/Documents/My Vault:/vault"
    environment:
      - NODE_ENV=development
      - OBSIDIAN_VAULT_PATH=/vault
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
